# Generated by Django 5.0.2 on 2024-02-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.ImageField(upload_to='files/'),
        ),
    ]
